version: 2

jobs:
  unit-test:
    macos:
      xcode: "13.3.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Install xcpretty
          command: gem install -N xcpretty
      - run:
          name: Run Tests
          command: xcodebuild -scheme LastMileUnitTests -destination "platform=macOS" test 2>&1 | xcpretty --simple -r junit
      - store_test_results:
          path: build/reports/
          destination: junit

workflows:
  version: 2
  unit-test:
    jobs:
      - unit-test
